spring.application.name=pfe
spring.datasource.url=jdbc:postgresql://localhost:5432/pfe_db
spring.datasource.username=postgres
spring.datasource.password=feriel2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082
spring.jwt.secret.key=mysecretkeysonelgaz123456789madebypfeproject
spring.jwt.date.expiration=86400000
